### ISSUE TITLE
this is awesome!

### ISSUE THREAD

**Issue by ladyada** [drewfish/arduino-ZeroRegs#2]
thanks for writing this, its really useful! we'll be adding this as a recommended debugging script in our "M0 arduino advice' page if that's cool with you :)
https://learn.adafruit.com/adafruit-feather-m0-express-designed-for-circuit-python-circuitpython/adapting-sketches-to-m0

**Comment by drewfish** [comment]
Cool, yeah published it to help whoever so feel free to send it around. Alas, I haven't worked on it much lately but very open to PRs.
